CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS QUALITY;

CREATE TABLE IF NOT EXISTS RAW.BATCH_EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  EVENT_DIGEST VARCHAR(64) NOT NULL,
  EVENT_TYPE VARCHAR(32) NOT NULL,
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  SITE_ID VARCHAR(64) NOT NULL,
  LINE_ID VARCHAR(64) NOT NULL,
  BATCH_ID VARCHAR(64) NOT NULL,
  MATERIAL_ID VARCHAR(64) NOT NULL,
  SOURCE_SYSTEM VARCHAR(64) NOT NULL,
  SEQUENCE_NO NUMBER(38, 0) NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_RAW_BATCH_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS QUALITY.DATA_QUALITY_ISSUE (
  ISSUE_ID VARCHAR(36) NOT NULL,
  EVENT_ID VARCHAR(64),
  ISSUE_CODE VARCHAR(64) NOT NULL,
  ISSUE_MESSAGE VARCHAR(1000) NOT NULL,
  RAW_DIGEST VARCHAR(64) NOT NULL,
  RECORDED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_DATA_QUALITY_ISSUE PRIMARY KEY (ISSUE_ID)
);

CREATE TABLE IF NOT EXISTS CURATED.BATCH_SNAPSHOT (
  BATCH_ID VARCHAR(64) NOT NULL,
  SITE_ID VARCHAR(64) NOT NULL,
  LINE_ID VARCHAR(64) NOT NULL,
  MATERIAL_ID VARCHAR(64) NOT NULL,
  STARTED_AT TIMESTAMP_TZ,
  RELEASED_AT TIMESTAMP_TZ,
  QUALITY_STATUS VARCHAR(16),
  COMPLETED_STEP_COUNT NUMBER(38, 0) NOT NULL,
  LATEST_SEQUENCE_NO NUMBER(38, 0) NOT NULL,
  LATEST_EVENT_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_EVENT_COUNT NUMBER(38, 0) NOT NULL,
  REFRESHED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT PK_BATCH_SNAPSHOT PRIMARY KEY (BATCH_ID)
);
