MERGE INTO CURATED.BATCH_SNAPSHOT AS TARGET
USING (
  WITH ORDERED_EVENTS AS (
    SELECT
      EVENT_ID,
      EVENT_TYPE,
      OCCURRED_AT,
      SITE_ID,
      LINE_ID,
      BATCH_ID,
      MATERIAL_ID,
      SEQUENCE_NO,
      PAYLOAD,
      ROW_NUMBER() OVER (
        PARTITION BY BATCH_ID
        ORDER BY OCCURRED_AT DESC, SEQUENCE_NO DESC, EVENT_ID DESC
      ) AS LATEST_ROW
    FROM RAW.BATCH_EVENT
    WHERE INGESTED_AT >= DATEADD('hour', -2, CURRENT_TIMESTAMP())
  ),

  AFFECTED_BATCHES AS (
    SELECT DISTINCT BATCH_ID
    FROM ORDERED_EVENTS
  )

  SELECT
    EVENTS.BATCH_ID,
    MAX_BY(EVENTS.SITE_ID, EVENTS.OCCURRED_AT) AS SITE_ID,
    MAX_BY(EVENTS.LINE_ID, EVENTS.OCCURRED_AT) AS LINE_ID,
    MAX_BY(EVENTS.MATERIAL_ID, EVENTS.OCCURRED_AT) AS MATERIAL_ID,
    MIN(IFF(EVENTS.EVENT_TYPE = 'BATCH_STARTED', EVENTS.OCCURRED_AT, NULL)) AS STARTED_AT,
    MAX(IFF(EVENTS.EVENT_TYPE = 'BATCH_RELEASED', EVENTS.OCCURRED_AT, NULL)) AS RELEASED_AT,
    MAX_BY(
      IFF(EVENTS.EVENT_TYPE = 'QUALITY_RECORDED', EVENTS.PAYLOAD:status::VARCHAR, NULL),
      IFF(EVENTS.EVENT_TYPE = 'QUALITY_RECORDED', EVENTS.OCCURRED_AT, NULL)
    ) AS QUALITY_STATUS,
    COUNT(DISTINCT IFF(
      EVENTS.EVENT_TYPE = 'STEP_COMPLETED',
      EVENTS.PAYLOAD:step_code::VARCHAR,
      NULL
    )) AS COMPLETED_STEP_COUNT,
    MAX(EVENTS.SEQUENCE_NO) AS LATEST_SEQUENCE_NO,
    MAX(EVENTS.OCCURRED_AT) AS LATEST_EVENT_AT,
    COUNT(*) AS SOURCE_EVENT_COUNT,
    CURRENT_TIMESTAMP() AS REFRESHED_AT
  FROM RAW.BATCH_EVENT AS EVENTS
  INNER JOIN AFFECTED_BATCHES
    ON EVENTS.BATCH_ID = AFFECTED_BATCHES.BATCH_ID
  GROUP BY EVENTS.BATCH_ID
) AS SOURCE
  ON TARGET.BATCH_ID = SOURCE.BATCH_ID
WHEN MATCHED THEN
  UPDATE SET
    TARGET.SITE_ID = SOURCE.SITE_ID,
    TARGET.LINE_ID = SOURCE.LINE_ID,
    TARGET.MATERIAL_ID = SOURCE.MATERIAL_ID,
    TARGET.STARTED_AT = SOURCE.STARTED_AT,
    TARGET.RELEASED_AT = SOURCE.RELEASED_AT,
    TARGET.QUALITY_STATUS = SOURCE.QUALITY_STATUS,
    TARGET.COMPLETED_STEP_COUNT = SOURCE.COMPLETED_STEP_COUNT,
    TARGET.LATEST_SEQUENCE_NO = SOURCE.LATEST_SEQUENCE_NO,
    TARGET.LATEST_EVENT_AT = SOURCE.LATEST_EVENT_AT,
    TARGET.SOURCE_EVENT_COUNT = SOURCE.SOURCE_EVENT_COUNT,
    TARGET.REFRESHED_AT = SOURCE.REFRESHED_AT
WHEN NOT MATCHED THEN INSERT (
  BATCH_ID,
  SITE_ID,
  LINE_ID,
  MATERIAL_ID,
  STARTED_AT,
  RELEASED_AT,
  QUALITY_STATUS,
  COMPLETED_STEP_COUNT,
  LATEST_SEQUENCE_NO,
  LATEST_EVENT_AT,
  SOURCE_EVENT_COUNT,
  REFRESHED_AT
)
VALUES (
  SOURCE.BATCH_ID,
  SOURCE.SITE_ID,
  SOURCE.LINE_ID,
  SOURCE.MATERIAL_ID,
  SOURCE.STARTED_AT,
  SOURCE.RELEASED_AT,
  SOURCE.QUALITY_STATUS,
  SOURCE.COMPLETED_STEP_COUNT,
  SOURCE.LATEST_SEQUENCE_NO,
  SOURCE.LATEST_EVENT_AT,
  SOURCE.SOURCE_EVENT_COUNT,
  SOURCE.REFRESHED_AT
);
